### ISSUE TITLE
System Information lightbox improvements

### ISSUE THREAD

**Issue by kmcbride3** [NestMTX/app#21]
## Describe the feature

When checking system information, the lightbox that loads is larger than the viewport using a 1920x1080 resolution with the browser maximized. This creates a double scrolling effect where you can scroll through the logging within the system information lightbox, but also have a scrollbar for the page, which is required to be scrolled down to see the latest log entries. To close the lightbox, you then must scroll back up to the top of the page to click the 'X' as it cannot be closed by hitting escape, unlike other lightboxes in NestMTX.

**Comment by jakguru** [comment]
I agree. The GUI logs interface needs to be tweaked a bit to make it more functional in general.
