### ISSUE TITLE
SRT output not disabled

### ISSUE THREAD

**Issue by tom42530** [NestMTX/app#41]
## Which version are you using?

latest
## Which operating system are you using?

- [ ] Linux amd64 standard
- [ *] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I'm trying to disable SRT output via MEDIA_MTX_SRT_ENABLED=false env variable but stream seems keep working

![image](https://github.com/user-attachments/assets/4d81d9e1-7fee-4ef8-bb46-ad8b7a8d581a)
 my env vars

ps output in container show ffmpeg process with srt :

![image](https://github.com/user-attachments/assets/c33a0bbf-5e68-4485-8d36-1693fb5064fc)

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by jakguru** [comment]
SRT cannot be disabled because it is used as the communication protocol from the internal processes INTO MediaMTX
